### ISSUE TITLE
Why MCP2120?

### ISSUE THREAD

**Issue by eos1d3** [Manawyrm/ESP32-IrDA-MCP2120#1]
I read your code and find this line:

`WRITE_PERI_REG( 0x3FF6E020 , READ_PERI_REG(0x3FF6E020) | (1<<16) );  //UART_IRDA_EN  "Let there be light"`

With the use of MCP2120, isn't it enough for ESP32 to setup as normal UART without IRDA enabled?

From this, it says MCP2120 is not used:

https://esp32.com/viewtopic.php?t=2766

**Comment by Manawyrm** [comment]
Hi! 

This project does not use a physical MCP2120 chip.
What this project does is, it emulates the protocol of an MCP2120 on the ESP32. 
This way you can connect a regular IrDA transceiver directly to the ESP32. 

Your computer (with Linux) can talk to the ESP from the kernel and it will think it's talking to an MCP2120-based converter, but it's really the ESP.

**Comment by eos1d3** [comment]
I am trying to connect a ST 8 bit micros (STM8S) to EPS32 via IrDA. Both devices has IrDA mode in UART. Your code helps and confirm ESP32 IrDA is easier that I expected.

PS: So surprised to get immediate response. Great thanks and very appreciated!!
